New stuff.
ascherer/cweb pull request #19
Opened 2021-03-14 16:49 UTC by texdraft

(Github is saying “Can't automatically merge”, but I don't understand why.  It's showing me differences that I don't think actually exist. Oh well. Sorry for any inconvenience.)

A high-level summary of the changes is in `my-changes.md`. Two new command-line options have been added (`q` and `t`). **There have been breaking changes to `cwebmac.tex` that go along with `CWEAVE`'s new literal support**. It will not work with documents woven using previous versions. I am completely open to ideas for altering the constant-related macros to maintain backwards-compatibility.

The attribute stuff and the numeric stuff has been tested fairly thoroughly; all the code examples from the C and C++ standards work well. Other things are less tested, but they are conservative enough that problems should arise only in extreme cases, unless of course there are silly mistakes somewhere.

The sequence of statements

```C
big_app1(pp); big_app(' '); big_app1(pp+1);
```

occurs nearly twenty times; I would make it a macro, but there is no precedent for doing so in the other production-related code.

Speaking of productions, `prod.w` is now pretty weird-looking, since a few dozen new entries are appended with seemingly no logical order. In fact, they represent some of the debugging process; productions after 143 were added as I found problems with the previous set.

Further changes will likely be to add support for other C++ constructs, like `concept` and `requires`. (C++ has apparently grown quite a bit in the last few years.) The `#define`-related quirks might be looked at as well.

2021-03-14 16:59 UTC, texdraft commented
… And I've just noticed an obvious error. Line 3087 of my `cweave.w` contains unreachable code, since `cat1` can't be `lbrack` if the earlier test `(cat1==lpar||cat1==lbrack)` at line 3085 has failed. The `||cat1==lbrack` should be removed. (The effect is the same, but it would cause the wrong production number to be shown in tracing.)

2021-03-14 17:29 UTC, ascherer commented
Please `rebase` on my `cweb-4.3-dev` to resolve the discrepancies.
* `git fetch upstream`
* `git rebase upstream/cweb-4.3-dev`

2021-03-14 17:44 UTC, texdraft commented
I regret to report that it says everything is up to date.

2021-03-14 18:39 UTC, ascherer commented
I've just commit the `big_app1_insert` macro in `cweave.w` to reduce code redundancy. Please refetch and rebase.

2021-03-14 19:24 UTC, ascherer commented
You obviously deleted a few spaces in various `function( /* comment` situations. Don't merge by hand. ;o)

2021-03-14 19:28 UTC, texdraft commented
Point taken `:)`. You have probably gathered that I'm not very experienced with git. Again I apologize for inconvenience; I now know enough so that it won't happen again.

2021-03-14 19:37 UTC, ascherer commented
`ctangle.w` looks clean, but `cweave.w` has several `<<<<<`, `=====`, `>>>>>` lines, i.e. unresolved conflicts.

2021-03-14 19:43 UTC, texdraft commented
Ugh. Don't ask how that happened.

2021-03-14 20:05 UTC, ascherer commented
* `cweave.w` still has `<<<<<`, `=====`, `>>>>>`.
* Please use `big_app1_insert` in your new code as far as possible.
* Please reinsert `\!` in `prod.w` to fix tabular alignment in table of productions.

2021-03-14 21:36 UTC, texdraft commented
OK. I also fixed overfull boxes in the production table caused by my additions.

2021-03-14 21:47 UTC, ascherer commented
* Line 3083: Is rule 144 actually triggered?
* Lines 3465 and 3468: Please align with other cases.

2021-03-14 21:59 UTC, texdraft commented
- It was not. Thanks for catching that oversight.
- OK.

2021-03-14 22:44 UTC, ascherer commented
We'll have to discuss your use of `flags['q']` and `flags['t']`, but other than that this looks just awesome!

2021-03-14 23:38 UTC, texdraft commented
Should they be made into macros? And thanks `:)`.

2021-03-15 07:38 UTC, ascherer commented
(1) Yes, macro replacements would be nice.
(2) I can/will replace option `-t` in [CWEBbin/TeX Live](https://github.com/ascherer/cwebbin/blob/master/comm-output.hch#L25) with NUWEB's option `-c`, so your use of `-t` in CWEAVE is OK.
(3) Your option `-q` is already taken by [CWEB in TeX Live](https://github.com/ascherer/cwebbin/blob/master/comm-texlive.ch#L239) and is no longer available.  Please consider a different flag.

I'll merge your excellent stuff RSN.  It'll take some time to integrate it in CWEBbin and TeX Live, though.

2021-03-15 07:41 UTC, ascherer commented
Please run `touch *.c`, `make`, `make cautiously`, and `make fullmanual` and check that all is clean.

2021-03-15 18:34 UTC, texdraft commented
It builds cleanly with no issues. I had to alter the manual very slightly to conform to the new macros for constants.

I've changed `q` to `k`, for “kwote” or “kill quotes”, and macrofied both uses of `flags`. The only change to any logic was to make `typename` work a little better. (Now it always creates an underlined index entry; the `t` switch controls only whether the identifier becomes a reserved word.)

2021-03-16 09:40 UTC, ascherer commented
Can you rebase once again, please? I had to revert a commit.

I'l process your submission later this week.

2021-03-16 15:42 UTC, ascherer requested changes
I'm sorry, but I really don't like how [this commit](https://github.com/ascherer/cweb/pull/19/commits/c0d544cdc8ec33419743d723f3881d12801eac73) modifies all **switch** constructs:
* all **case**: statements are indented
* all **case**: statements are surrounded by extra vertical space

Please restore former behavior.

2021-03-16 21:29 UTC, texdraft commented
Yikes. I didn't intend to change the behavior. The culprit was the innocuous production 156. It was intended to allow `public: }`, which without it would have been treated as a malformed statement instead of as an empty declaration. But the production fired too early and its effects propagated throughout the entire `switch`. Now the output is as before and looks much better (and the new tests aren't affected). I was so confident my changes didn't break anything that I somehow didn't notice the difference.

2021-03-17 10:21 UTC, ascherer commented
Although your branch `cweb-4.3-dev` _could_ be merged into my `cweb-4.3-dev`, I'd rather like to have it **rebased** to the `HEAD` of my `cweb-4.3-dev`. My intermediate commits and revertions should be excluded from your pull request:
```
git checkout master
git bramch -M cweb-4.3-dev my-cweb-4.3-dev # move to a new name
git remote add upstream https://github.com/ascherer/cweb
git fetch upstream
git rebase upstream/master # should be clean
git checkout -b cweb-4.3-dev # new branch of the same name!
git branch -u upstream/cweb-4.3-dev
git pull --rebase # gets the HEAD of my cweb-4.3-dev
git checkout my-cweb-4.3-dev
git rebase cweb-4.3-dev # there are merge conflicts to resolve
```
When `my-cweb-4.3-dev` is up-to-date, you can
```
git checkout master
git branch -D cweb-4.3-dev
git branch -M my-cweb-4.3-dev cweb-4.3-dev
git branch -u origin/cweb-4.3-dev
git push -f
```
Good luck!

2021-03-17 16:45 UTC, ascherer commented
Your branch is not fully based on my `cweb-4.3-dev`, because your version has all `\1\1` and `\2\2` in function headers removed. I reverted the simple solution for parameter indentation and restored the old, manually indented, function headers, because it created really bad TeX code.

The culprit seems to be [this commit](https://github.com/texdraft/cweb/commit/1a50740fe87a9af632d1e217d8594b1d3fa7a03d).

2021-03-17 17:47 UTC, ascherer commented
Thanks. I'll work on your PR later this week.

2021-03-17 17:49 UTC, texdraft commented
I get the feeling that most pull requests aren't this torturous. Thanks for bearing with me.

2021-03-19 07:56 UTC, merged

2021-03-19 11:14 UTC, ascherer commented
@texdraft I believe to have fully integrated your fine material in [CWEB 4.3/dev](https://github.com/ascherer/cweb/tree/cweb-4.3-dev) and [CWEBbin](https://github.com/ascherer/cwebbin/tree/cweb-4.3).  Please check for consistency.

2021-03-19 21:54 UTC, texdraft commented
@ascherer Yes, it all looks good. Good idea to invert the sense of the `k` switch.

2021-05-02 12:51 UTC, ascherer commented
@texdraft We have a serious problem with [this commit](https://github.com/ascherer/cweb/commit/ebee84dc2449283831abe889931ba8982fb61d23) in **CWEB 4.3**:

1.  It overrides the `@d`efinition of, e.g., `max_toks` from section **17** in `cweave.w` with the **use** of `max_toks` in section **30** and puts this secondary _re_-definition underlined in the index.
2. `CTWILL` unravels this bug in the mini-indexes by showing the definition of `max_toks` as “**static token** [], §30.”, which is, of course, utterly incorrect.  (It should be listed as “1000000, §17”.)
3. While it is possible – albeit clumbsy – to fix in `CTWILL` output, the incorrectly underlined section numbers in `CWEAVE` output can't be remedied without your deeper insight.

Please take a look at this problem.  Thanks.

2021-05-02 20:32 UTC, texdraft commented
@ascherer In `weave.w`:

```
@x
else if (cat1==exp && cat2!=lpar && cat2!=exp && cat2!=cast) {
@y
else if (cat1==exp && cat2!=lpar && cat2!=exp && cat2!=cast && cat2!=lbrack) {
@z
```

In `prod.w`:

```
@x
Rule 35: The |exp| must not be immediately followed by |lpar|, |exp|,
 or~|cast|.
@y
Rule 35: The |exp| must not be immediately followed by |lpar|, |exp|, |lbrack|,
 or~|cast|.
@z
```

- Production 35 turns `decl_head exp` into `decl_head`, after underlining the first identifier in `exp`.
- But this would cause spurious indexing if another expression follows, as in `decl_head exp exp`.
- So a safeguard was included, ensuring that the `exp` would be given a good chance to merge with any following material.
- My changes broke it by differentiating `[` and `]` from `(` and `)`, so that the check for `lpar` wasn't sufficient. Sorry! I didn't expect there to be any effect on the indexing behavior&hellip;

2021-05-02 21:11 UTC, ascherer commented
Will check on Wednesday. Until then thanks!

2021-05-03 07:18 UTC, ascherer commented
Branch [`cweb-4.3-dev`](https://github.com/ascherer/cweb/tree/cweb-4.3-dev) is clean again. I've incorporated all changes – apart from "version 4.4" – from branch [`cweb-4.4-dev`](https://github.com/ascherer/cweb/tree/cweb-4.4-dev). I'll bubble up **CWEB 4.3 (May 2021)** into **CWEBbin** and **TeX Live** on Wednesday. Thanks for the quick response.

2021-05-03 13:43 UTC, ascherer commented
Done.

2021-05-03 17:06 UTC, ascherer commented
[Excellence has been achieved](https://github.com/ascherer/cwebbin/releases/download/cwebbin-2021.3.1/ctwill.pdf)!